// import * as helper from '../src/utils/request'
// import parse from 'url-parse'
//
// describe('.isValidResponse', () => {
//   it('returns true if valid', () => {
//     const rsp = {
//       header: {
//         'content-type': 'text/javascript',
//         'content-disposition': 'inline'
//       }
//     }
//
//     expect(helper.isValidResponse(rsp)).toBe(true)
//   })
//
//   it('returns false when disposition is attachment', () => {
//     const rsp = {
//       header: {
//         'content-type': 'text/javascript',
//         'content-disposition': 'attachment'
//       }
//     }
//
//     expect(helper.isValidResponse(rsp)).toBe(false)
//   })
//
//   it('returns false when content-type is not javascript', () => {
//     const rsp = {
//       header: {
//         'content-type': 'text/html',
//         'content-disposition': 'inline'
//       }
//     }
//
//     expect(helper.isValidResponse(rsp)).toBe(false)
//   })
// })
//
// describe('.parseSJR', () => {
//   it('evals content generated by BreezyTemplates', () => {
//     const body = ` (function() {
//         return {
//           data: { heading: 'Some heading 2' },
//           title: 'title 2',
//           csrf_token: 'token',
//           assets: ['application-123.js', 'application-123.js']
//         };
//       })();
//     `
//     const parsed = helper.parseSJR(body)
//     expect(parsed.data.heading).toEqual('Some heading 2')
//   })
// })
//
