source 'https://rubygems.org'
gemspec
gem 'rails'
gem 'sqlite3'
gem "mocha", :require => false
gem 'rake'
gem 'sprockets'
gem 'coffee-script'
gem 'coffee-script-source', '~> 1.9.1'
gem 'eco'
gem 'uglifier'
gem 'pry'

gem 'blade', git: 'https://github.com/jho406/blade', branch: 'switch_to_puma_070'
gem 'blade-sauce_labs_plugin'
gem 'byebug'
