package main

import (
	"strings"

	shimast "github.com/microsoft/typescript-go/shim/ast"
	shimprinter "github.com/microsoft/typescript-go/shim/printer"
	shimscanner "github.com/microsoft/typescript-go/shim/scanner"
	"github.com/samchon/ttsc/packages/ttsc/driver"
	nativecontext "github.com/samchon/typia/packages/typia/native/core/context"
	nativeprogrammers "github.com/samchon/typia/packages/typia/native/core/programmers"
	nativetransform "github.com/samchon/typia/packages/typia/native/transform"
)

// transformFileToTypeScript runs the useContent rewriter on one source file in
// a fresh EmitContext and prints the result as TypeScript (no JS transforms).
//
// When a driver.Program is available, it directly calls typia's
// ValidateProgrammer to generate inline validation code. Without a program
// (e.g. in unit tests), it falls back to inserting typia.createValidate<T>().
func transformFileToTypeScript(
	prog *driver.Program,
	sf *shimast.SourceFile,
	transformDiags *[]transformDiagnostic,
) string {
	options := prog.TSProgram.Options()
	ec := shimprinter.NewEmitContext()

	extras := nativecontext.ITypiaContext_Extras{}
	if transformDiags != nil {
		extras.AddDiagnostic = func(diag *nativecontext.ITypiaDiagnostic) int {
			*transformDiags = append(*transformDiags, transformDiagnosticFrom(diag))
			return len(*transformDiags)
		}
	}

	ctx := nativecontext.ITypiaContext{
		Program:         prog,
		CompilerOptions: options,
		Checker:         prog.Checker,
		Options:         nativecontext.ITransformOptions{},
		Emit:            ec,
		Extras:          extras,
	}

	// Step 1: Run typia's transform on the ORIGINAL AST first.
	typiaTransform := nativetransform.Transform(prog, &ctx.Options, extras, ec)
	result := sf
	if next := typiaTransform(result); next != nil {
		result = next
	}

	// Step 2: Run our useContent/useFragment rewrite on the result.
	result = transformSourceFileWithTypia(ec, result, &ctx)

	shimast.SetParentInChildrenUnset(result.AsNode())
	writer := shimprinter.NewTextWriter(options.NewLine.GetNewLineCharacter(), 0)
	printer := shimprinter.NewPrinter(
		shimprinter.PrinterOptions{NewLine: options.NewLine},
		shimprinter.PrintHandlers{},
		ec,
	)
	printer.Write(result.AsNode(), result, writer, nil)
	return writer.String()
}

// transformSourceFileWithTypia walks the AST of a single source file and
// rewrites useContent<T>() calls. When a ITypiaContext is available (has a
// checker), it generates inline validation code directly via typia's
// ValidateProgrammer. Otherwise falls back to inserting
// typia.createValidate<T>().
func transformSourceFileWithTypia(
	ec *shimprinter.EmitContext,
	sf *shimast.SourceFile,
	ctx *nativecontext.ITypiaContext,
) *shimast.SourceFile {
	f := &ec.Factory.NodeFactory

	var visitor *shimast.NodeVisitor
	visit := func(node *shimast.Node) *shimast.Node {
		if node == nil {
			return nil
		}
		if node.Kind == shimast.KindCallExpression {
			if rewritten := rewriteUseContentCallWithTypia(f, node.AsCallExpression(), ctx); rewritten != nil {
				// Don't recurse into the rewritten node — it may contain
				// synthetic nodes from ValidateProgrammer that lack source
				// file references and would panic in GetTextOfNode.
				return rewritten
			}
		}
		return visitor.VisitEachChild(node)
	}

	visitor = ec.NewNodeVisitor(visit)
	output := visitor.VisitNode(sf.AsNode())
	if output == nil {
		return sf
	}
	return output.AsSourceFile()
}

// transformSourceFile walks the AST without typia context — used by unit tests.
// Produces typia.createValidate<T>() calls (Part 2 output).
func transformSourceFile(
	ec *shimprinter.EmitContext,
	sf *shimast.SourceFile,
) *shimast.SourceFile {
	return transformSourceFileWithTypia(ec, sf, nil)
}

// rewriteUseContentCallWithTypia checks if a CallExpression is a
// useContent<T>() call and rewrites it. When ctx has a checker, it generates
// inline validation via typia's ValidateProgrammer (Part 3). Otherwise
// inserts typia.createValidate<T>() (Part 2).
func rewriteUseContentCallWithTypia(
	f *shimast.NodeFactory,
	call *shimast.CallExpression,
	ctx *nativecontext.ITypiaContext,
) *shimast.Node {
	if call == nil {
		return nil
	}

	expr := call.Expression
	if expr == nil || expr.Kind != shimast.KindIdentifier {
		return nil
	}
	// Skip synthetic nodes — they were generated by a prior transform
	// (e.g. typia's IIFE) and GetTextOfNode would panic on them.
	if expr.Flags&shimast.NodeFlagsSynthesized != 0 {
		return nil
	}
	name := shimscanner.GetTextOfNode(expr)
	isUseContent := name == "useContent"
	isUseFragment := name == "useFragment"
	if !isUseContent && !isUseFragment {
		return nil
	}

	if call.TypeArguments == nil || len(call.TypeArguments.Nodes) == 0 {
		return nil
	}

	// Skip if already has 2+ arguments (matches deepkit's node.arguments.length < 2 check).
	if call.Arguments != nil && len(call.Arguments.Nodes) >= 2 {
		return nil
	}

	typeArgNode := call.TypeArguments.Nodes[0]

	// Build the validate expression — either inline IIFE or typia.createValidate<T>()
	var validateExpr *shimast.Node

	if ctx != nil && ctx.Checker != nil {
		// Generate inline validation via typia's ValidateProgrammer.
		// StandardSchema: false gives us (input) => IValidation<T> directly.
		typ := ctx.Checker.GetTypeFromTypeNode(typeArgNode)
		if typ != nil {
			typeName := strings.TrimSpace(shimscanner.GetTextOfNode(typeArgNode))
			validateExpr = nativeprogrammers.ValidateProgrammer.Write(nativeprogrammers.ValidateProgrammer_IProps{
				Context: *ctx,
				Type:    typ,
				Name:    &typeName,
				Config: nativeprogrammers.ValidateProgrammer_IConfig{
					Equals:         false,
					StandardSchema: false,
				},
			})
		}
	}

	if validateExpr == nil {
		// Fallback (Part 2): Insert typia.createValidate<T>()
		typiaAccess := f.NewPropertyAccessExpression(
			f.NewIdentifier("typia"),
			nil,
			f.NewIdentifier("createValidate"),
			shimast.NodeFlagsNone,
		)
		validateExpr = f.NewCallExpression(
			typiaAccess,
			nil,
			f.NewNodeList([]*shimast.Node{typeArgNode}),
			f.NewNodeList([]*shimast.Node{}),
			shimast.NodeFlagsNone,
		)
	}

	// Wrap the validator in a function that logs errors in [Superglue] format.
	// The validate option expects (data: unknown) => void. The typia validator
	// returns IValidation<T> = { success, errors?, data }. This wrapper calls
	// it and console.error's on failure, matching the deepkit plugin's behavior.
	//
	// Output:
	//   (function() {
	//     var __sg_v = <validateExpr>;
	//     return function(data) {
	//       var result = __sg_v(data);
	//       if (!result.success) {
	//         console.error("[Superglue] Content validation failed:", result.errors.map(function(e) {
	//           return { path: e.path, message: e.message };
	//         }));
	//       }
	//     };
	//   })()
	validateExpr = wrapWithSuperglueLogging(f, validateExpr)

	// Build: { validate: <validateExpr> }
	validateProp := f.NewPropertyAssignment(
		nil,
		f.NewIdentifier("validate"),
		nil,
		nil,
		validateExpr,
	)
	optionsObj := f.NewObjectLiteralExpression(
		f.NewNodeList([]*shimast.Node{validateProp}),
		false,
	)

	// Build args: preserve existing arguments, then append options.
	// useContent with 0 args needs an explicit undefined placeholder for pageKey.
	var args []*shimast.Node
	if call.Arguments != nil && len(call.Arguments.Nodes) > 0 {
		args = append(args, call.Arguments.Nodes[0])
	} else if isUseContent {
		args = append(args, f.NewIdentifier("undefined"))
	}
	args = append(args, optionsObj)

	return f.NewCallExpression(
		expr,
		nil,
		call.TypeArguments,
		f.NewNodeList(args),
		shimast.NodeFlagsNone,
	)
}

// wrapWithSuperglueLogging wraps a typia validator expression in an IIFE that
// calls the validator and logs errors in [Superglue] format. The validate
// option expects (data: unknown) => void; the typia validator returns
// IValidation<T> = { success, errors?, data }. This wrapper bridges the gap.
func wrapWithSuperglueLogging(f *shimast.NodeFactory, validateExpr *shimast.Node) *shimast.Node {
	// var __sg_v = <validateExpr>;
	varDecl := f.NewVariableStatement(
		nil,
		f.NewVariableDeclarationList(
			f.NewNodeList([]*shimast.Node{
				f.NewVariableDeclaration(f.NewIdentifier("__sg_v"), nil, nil, validateExpr),
			}),
			shimast.NodeFlagsNone,
		),
	)

	// var result = __sg_v(data);
	resultDecl := f.NewVariableStatement(
		nil,
		f.NewVariableDeclarationList(
			f.NewNodeList([]*shimast.Node{
				f.NewVariableDeclaration(
					f.NewIdentifier("result"), nil, nil,
					f.NewCallExpression(
						f.NewIdentifier("__sg_v"),
						nil, nil,
						f.NewNodeList([]*shimast.Node{f.NewIdentifier("data")}),
						shimast.NodeFlagsNone,
					),
				),
			}),
			shimast.NodeFlagsNone,
		),
	)

	// function(e) { return { path: e.path, message: e.message }; }
	mapCallback := f.NewFunctionExpression(
		nil, nil, nil, nil,
		f.NewNodeList([]*shimast.Node{
			f.NewParameterDeclaration(nil, nil, f.NewIdentifier("e"), nil, nil, nil),
		}),
		nil, nil,
		f.NewBlock(
			f.NewNodeList([]*shimast.Node{
				f.NewReturnStatement(
					f.NewObjectLiteralExpression(
						f.NewNodeList([]*shimast.Node{
							f.NewPropertyAssignment(nil, f.NewIdentifier("path"), nil, nil,
								f.NewPropertyAccessExpression(f.NewIdentifier("e"), nil, f.NewIdentifier("path"), shimast.NodeFlagsNone)),
							f.NewPropertyAssignment(nil, f.NewIdentifier("message"), nil, nil,
								f.NewPropertyAccessExpression(f.NewIdentifier("e"), nil, f.NewIdentifier("message"), shimast.NodeFlagsNone)),
						}),
						false,
					),
				),
			}),
			false,
		),
	)

	// console.error("[Superglue] Content validation failed:", result.errors.map(...))
	consoleError := f.NewCallExpression(
		f.NewPropertyAccessExpression(
			f.NewIdentifier("console"), nil, f.NewIdentifier("error"), shimast.NodeFlagsNone,
		),
		nil, nil,
		f.NewNodeList([]*shimast.Node{
			f.NewStringLiteral("[Superglue] Content validation failed:", shimast.TokenFlagsNone),
			f.NewCallExpression(
				f.NewPropertyAccessExpression(
					f.NewPropertyAccessExpression(
						f.NewIdentifier("result"), nil, f.NewIdentifier("errors"), shimast.NodeFlagsNone,
					),
					nil, f.NewIdentifier("map"), shimast.NodeFlagsNone,
				),
				nil, nil,
				f.NewNodeList([]*shimast.Node{mapCallback}),
				shimast.NodeFlagsNone,
			),
		}),
		shimast.NodeFlagsNone,
	)

	// if (!result.success) { console.error(...); }
	ifStmt := f.NewIfStatement(
		f.NewPrefixUnaryExpression(
			shimast.KindExclamationToken,
			f.NewPropertyAccessExpression(
				f.NewIdentifier("result"), nil, f.NewIdentifier("success"), shimast.NodeFlagsNone,
			),
		),
		f.NewBlock(
			f.NewNodeList([]*shimast.Node{f.NewExpressionStatement(consoleError)}),
			false,
		),
		nil,
	)

	// return function(data) { var result = __sg_v(data); if (!result.success) { ... } };
	innerFn := f.NewFunctionExpression(
		nil, nil, nil, nil,
		f.NewNodeList([]*shimast.Node{
			f.NewParameterDeclaration(nil, nil, f.NewIdentifier("data"), nil, nil, nil),
		}),
		nil, nil,
		f.NewBlock(
			f.NewNodeList([]*shimast.Node{resultDecl, ifStmt}),
			true,
		),
	)

	// (function() { var __sg_v = <expr>; return function(data) { ... }; })()
	outerFn := f.NewFunctionExpression(
		nil, nil, nil, nil,
		f.NewNodeList([]*shimast.Node{}),
		nil, nil,
		f.NewBlock(
			f.NewNodeList([]*shimast.Node{varDecl, f.NewReturnStatement(innerFn)}),
			true,
		),
	)

	return f.NewCallExpression(
		f.NewParenthesizedExpression(outerFn),
		nil, nil,
		f.NewNodeList([]*shimast.Node{}),
		shimast.NodeFlagsNone,
	)
}

// looksLikeValidateArg checks if a node is an object literal containing a
// "validate" property. Used to detect already-rewritten calls.
func looksLikeValidateArg(node *shimast.Node) bool {
	if node == nil || node.Kind != shimast.KindObjectLiteralExpression {
		return false
	}
	found := false
	node.ForEachChild(func(child *shimast.Node) bool {
		if shimast.IsPropertyAssignment(child) {
			propName := child.PropertyName()
			if propName != nil && shimscanner.GetTextOfNode(propName) == "validate" {
				found = true
				return true
			}
		}
		return false
	})
	return found
}
