require 'rake/testtask'

task :generate_blade_yml do
  root = File.expand_path(File.dirname(__FILE__))
  file = File.join(root, 'blade.yml.erb')
  blade_yml = ERB.new(File.read(file)).result

  File.write("#{File.join(root, "blade.yml")}", blade_yml)
end

namespace :dummy do
  require_relative "test/dummy/application"
  Dummy::Application.load_tasks

  task :server do
    require "rails/all"
    require_relative "test/dummy/application"
    Dummy::Application.initialize!
  end
end
