# frozen_string_literal: true

# This file was copied over from Rails land and slightly modified to account
# for Superglue templates

require "rails/generators/resource_helpers"
require "rails/generators/rails/scaffold_controller/scaffold_controller_generator"

module Superglue
  module Generators
    class ScaffoldControllerGenerator < Rails::Generators::NamedBase # :nodoc:
      include Rails::Generators::ResourceHelpers

      # Superglue uses the out-of-the-box controller generated by Rails.
      source_root Rails::Generators::ScaffoldControllerGenerator.source_root

      check_class_collision suffix: "Controller"

      class_option :helper, type: :boolean
      class_option :orm, banner: "NAME", type: :string, required: true,
                         desc: "ORM to generate the controller for"

      class_option :skip_routes, type: :boolean, desc: "Don't add routes to config/routes.rb."

      argument :attributes, type: :array, default: [], banner: "field:type field:type"

      def create_controller_files
        template "controller.rb", File.join("app/controllers", controller_class_path, "#{controller_file_name}_controller.rb")
      end

      # Replaces template_engine (and its default erb), with view_collection
      # defaulting to superglue:view_collection
      hook_for :view_collection, required: true, default: "view_collection"

      hook_for :resource_route, in: :rails, required: true do |route|
        invoke route unless options.skip_routes?
      end

      hook_for :test_framework, in: :rails, as: :scaffold

      # Invoke the helper using the controller name (pluralized)
      hook_for :helper, in: :rails, as: :scaffold do |invoked|
        invoke invoked, [controller_name]
      end

      private

        def permitted_params
          attachments, others = attributes_names.partition { |name| attachments?(name) }
          params = others.map { |name| ":#{name}" }
          params += attachments.map { |name| "#{name}: []" }
          params.join(", ")
        end

        def attachments?(name)
          attribute = attributes.find { |attr| attr.name == name }
          attribute&.attachments?
        end
    end
  end
end
